# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev7+g97fb68d.d20220906'
__version_tuple__ = version_tuple = (0, 1, 'dev7', 'g97fb68d.d20220906')
